### ISSUE TITLE
Add more info before 1.11.0 release, how to trigger a new release

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2tmpl#105]
@AndrewBenjamin-NOAA says:

> I will have a few items to add to the g2tmpl shortly. 

Andrew, I am ready for a release. Do you want to submit any updates?

@AndrewBenjamin-NOAA also says:

> From a grib2 documentation and products perspective, I update local use grib2 products as those requests come to me. But for products used internationally, the WMO updates and releases versions of their grib2 tables in May and November every year.
> 
> I was wondering how difficult it would be to consider getting on a similar (but staggered) release cadence for g2tmpl? For example, If the WMO releases their update on time in mid-November,  I will update the NCEP documentation and make additions to the g2tmpl. Then would it be possible to release sometime Dec-Feb? I'm sure getting it onto WCOSS2 is much more of a process than the R&D machines, but I don't know how difficult the process is overall.

When making additions to g2tmpl please make also add test code which checks those values. There is existing test code to see as an example, or else just ask for help when you need it. All code changes require testing, are subject to code review, and must pass the CI system, which includes memory, warnings, and documentation check. PRs which do not pass these tests cannot be merged.

The process for doing a release is very simple and takes only minutes. Because the repo is always kept ready  for release, we can do a release at any time by:
* updating the documentation on the gh-pages branch.
* updating the release notes with any important changes.
* hitting the release button.
* setting up the project/release notes for the next release.

If you want me to do a release, then add an issue, for example, #94. We absolutely can do releases on the schedule you mention.

Once we do a release, we (the NCEPLIBS team) also update the spack package file which installs g2tmpl. This takes some time to percolate through the research systems as you note. @AlexanderRichert-NOAA is the person who will step in if anything goes wrong, but once the spack files are updated, then the new release will be automatically installed by the GDIT group - Alex, do I have that correct?

Installing on WCOSS2 is a whole separate process, which is done by @Hang-Lei-NOAA. So we must notify him when there is a new release so he can submit it correctly to NCO for installation on WCOSS2.

**Comment by AlexanderRichert-NOAA** [comment]
As far as installations on the R&D systems, the spack-stack team does quarterly installations on all the [platofrms](https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html). We generally try to use the latest versions, but to ensure that a particular package/version make it in there, it's best to file an [issue](https://github.com/JCSDA/spack-stack/issues/new?assignees=Hang-Lei-NOAA%2C+AlexanderRichert-NOAA%2C+jkbk2004%2C+climbfuji&labels=install&projects=&template=install_request.md&title=%5BINSTALL%5D+%3Ctitle%3E) requesting the installation. That will take care of getting a new version onto Hera, Orion, etc. (and in "emergencies" can be done fairly quickly, but generally it's on a quarterly basis). Then as you say Ed, getting a package installed on WCOSS2 is a separate process requested through Hang, and executed ultimately on the NCO side by GDIT where the installations will live in a test space until they're needed in operations.

**Comment by edwardhartnett** [comment]
@AndrewBenjamin-NOAA do you have any changes you want to put into the repo before I do a release? I'd like to do the release next week...

**Comment by AndrewBenjamin-NOAA** [comment]
@edwardhartnett Yes I have at least one product to add. I should be able to have everything in by Wednesday, is that ok?

**Comment by edwardhartnett** [comment]
Yes, that's fine. As soon as you have everything in that you want, we will do a release.

**Comment by AndrewBenjamin-NOAA** [comment]
@edwardhartnett one PR is submitted, with probably 1-2 more tomorrow. They are mostly adding new parameters, so hopefully the checks on your end will be minimal.

**Comment by AndrewBenjamin-NOAA** [comment]
@edwardhartnett I have finished with the updates.  PR (https://github.com/NOAA-EMC/NCEPLIBS-g2tmpl/pull/106) is submitted and complete.
