### ISSUE TITLE
RRFS UPP needs to use product definition template 4.9

### ISSUE THREAD

**Issue by EricJames-NOAA** [NOAA-EMC/NCEPLIBS-g2tmpl#113]
UPP needs access to GRIB2 product definition template 4.9 for some new RRFS forecast products.  I'm not sure what is involved in adding this, or how current GRIB2 output of probabilistic fields (e.g., for HREF) is created.

https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-9.shtml

**Comment by edwardhartnett** [comment]
This is working and has been tested by UPP team.
