### ISSUE TITLE
do a 1.12.0 release

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2tmpl#126]
Looks like we need another release to get the 4.9 and 4.46 templates out there.

@EricJames-NOAA and @WenMeng-NOAA is there anything else you would like to get into g2tmpl before the next release?

**Comment by WenMeng-NOAA** [comment]
@edwardhartnett From the UPP code manager perspective, the new commits in the current develop branch should be sufficient to support RRFS scientific code freezing. @EricJames-NOAA may chime in.

**Comment by edwardhartnett** [comment]
Steps to release:
* Change the VERSION file.
* Make sure release notes are up to date.
* Manage github project, clearing all issues for this release, closing project.
* Build and update documentation on gh-pages branch (including link to past version of docs).
* Do release.
* Draft release notes for next release, start project for next release.
* After release, update spack file.
