### ISSUE TITLE
 Adding GRIB2 template 4.49 for GEFSv13 aerosol ensemble use.

### ISSUE THREAD

**Issue by bingfu-NOAA** [NOAA-EMC/NCEPLIBS-g2tmpl#132]
[GRIB2 table 4.49](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-49.shtml) is missing in g2tmpl source code.
GEFSv13 ensemble aerosol products can not be correctly generated.

**Comment by edwardhartnett** [comment]
Can you add this info?

**Comment by edwardhartnett** [comment]
OK, I have added this. Is this for the UPP?

**Comment by bingfu-NOAA** [comment]
Yes, it it. I am adding Li @lipan-NOAA here, he has been working on this.
