### ISSUE TITLE
Add template 4.49

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/NCEPLIBS-g2tmpl#135]
To encode ensemble member information in aerosol fields, the [template 4.49](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-49.shtml) should be added in grib2_all_tables_module.F90.

**Comment by edwardhartnett** [comment]
I have a PR up for this now, and can do a release and we can get this installed for you to try out.

Where in the UPP is this code going to be called? I would like to look at how you call g2tmpl.

Do you have any files which use this template? That is, are there any existing files I can test with?

**Comment by WenMeng-NOAA** [comment]
@edwardhartnett Please add @lipan-NOAA for reviewing and testing your PR. He has workarounds for running UPP to output aerosol fields in including ensemble member information.

**Comment by WenMeng-NOAA** [comment]
@edwardhartnett This g2tmpl update has a decency on g2 update. We would like the g2 release to go first.
