### ISSUE TITLE
Is one line of MSTAV redundant in src/params_grib2_tbl_new?

### ISSUE THREAD

**Issue by YaliMao-NOAA** [NOAA-EMC/NCEPLIBS-g2tmpl#143]
I experienced a confusing result when coding and decoding a grib2 file with MSTAV field.
According to the grib2 table, https://github.com/NOAA-EMC/NCEPLIBS-g2tmpl/blob/develop/src/params_grib2_tbl_new, there are three lines of MSTAV.
   2   0    11   0 MSTAV
   2   0   194   1 MSTAV
   2   3   204   1 MSTAV

In HRRR UPP, /lfs/h1/ops/prod/packages/hrrr.v4.1.17/parm/conus/hrrr_params_grib2_tbl_new, there are two lines of MSTAV
   2   0    11   0 MSTAV
   2   0   194   1 MSTAV

Here is the situation. In UPP, a field is determined by a mnemonic, for example MSTAV in question. The whole table,  params_grib2_tbl_new, will be searched through and the last line of MSTAV will be the one for UPP grib2 output, with its corresponding discipline number, category number and parameter number.

I assume no issue if all the mnemonics in params_grib2_tbl_new are unique. However there are multiple lines of MSTAV, and your version and HRRR version tables end with different lines of MSTAV. So I got different/confusing outputs by using two different versions of params_grib2_tbl_new.

My question is: should all the mnemonics in params_grib2_tbl_new be unique to avoid such kind of confusion?

Thank you!
Yali

**Comment by edwardhartnett** [comment]
My understanding is that parameters may be added as local GRIB2 parameters, then later made into official GRIB2 parameters. IN that case, the earlier entry in the table will refer to the local one and the later entry the official one. Since the latest entry is used, the official one is always used. But the local one is still understood as needed.

Does that make sense?

We inherited this code from other and do not have a good idea of it's use or development...

**Comment by YaliMao-NOAA** [comment]
@edwardhartnett Thank you. I will find other solutions given your explanations. Closing this issue

**Comment by edwardhartnett** [comment]
We are working on a refactor of our WMO codes and how we handle updates. @AlysonStahl-NOAA is working on this actively.

Can you tell us what you want the library to do, that it's not doing?

**Comment by YaliMao-NOAA** [comment]
I am expecting the grib2 table list to have these two features:
1. A mnemonics is either unique
2. If not unique, this mnemonics has at most two lines of entries, one is local, the other is public/official.
Can it happen?
