### ISSUE TITLE
New parameters and generating Process ID

### ISSUE THREAD

**Issue by BoiVuong-NOAA** [NOAA-EMC/NCEPLIBS-g2tmpl#24]
-Request a new Generating Process/Model ID for Rapid Refresh Forecast System (RRFS) in ON388 - tableA
and some new parameters for models AQ, 3D-RTMA and RRFS in GRIB2 tables 4.2

**Comment by BoiVuong-NOAA** [comment]
I will update two files in g2tmpl and will give it to you on Monday.

**Comment by kgerheiser** [comment]
Fixed with release of v1.10.0 and associated PRs
