### ISSUE TITLE
Incorrect versioning

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-g2tmpl#27]
Boi just released `g2tmpl_v1.9.0` as a tag, but we already have a `v1.9.0` (and `v1.9.1`) as releases (https://github.com/NOAA-EMC/NCEPLIBS-g2tmpl/releases)

The should be version 1.10.0 or 1.9.2 and an actual release instead of just a tag.

@BoiVuong-NOAA @edwardhartnett @Hang-Lei-NOAA

**Comment by BoiVuong-NOAA** [comment]
created a tag g2tmpl_v1.10.0

**Comment by kgerheiser** [comment]
Fixed with a release and the incorrect tags have been deleted
