### ISSUE TITLE
Determine what applications are using g2tmpl, and what parts of g2tmpl are being used.

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2tmpl#29]
Determine what applications are using g2tmpl, and what parts of g2tmpl are being used.

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA can you describe how this project is used?

What other projects are using g2tmpl?

**Comment by BoiVuong-NOAA** [comment]
The g2tmpl library uses in models: HRRR, WRF, NCEP POST, RFS, UFS.  I do not know the details please ask Wen.

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA you can use the at-sign to tag others. Please do so.

@WenMeng-NOAA can you explain what models or other applications at NOAA use the NCEPLIBS-g2tmpl library?

**Comment by WenMeng-NOAA** [comment]
@edwardhartnett The g2tmpl has been used in all FV3 based applications, like GFSV17, RRFS, HAFS, and other applications like RAP/HRRR, RTMA, NAM.

**Comment by edwardhartnett** [comment]
Thanks I have updated the README with this info.

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA what is "RFS"?

**Comment by BoiVuong-NOAA** [comment]
It should be RRFS (Rapid Refresh Forecast System).
