### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2tmpl#36]
We need testing for this code.

**Comment by edwardhartnett** [comment]
OK, we have one unit test running, but it is an empty test. Meanwhile, @BoiVuong-NOAA has some test code, but we are not running it in CI.

Boi, which of the .f90 files in tests should be run as tests. All of them?

```
  -rwxrwxr-x 1 ed ed 11470 Oct  9  2020 test_g2tmpl_pdt4_11.f90
  -rwxrwxr-x 1 ed ed  6898 Oct  9  2020 test_g2tmpl_pdt4_12.f90
  -rwxrwxr-x 1 ed ed  2542 Oct  9  2020 test_g2tmpl_pdt4_1.f90
  -rwxrwxr-x 1 ed ed  3682 Oct  9  2020 test_g2tmpl_pdt4_8.f90
  -rwxrwxr-x 1 ed ed  1097 Oct  9  2020 test_g2tmpl_table_233.f90
  -rwxrwxr-x 1 ed ed  2451 Oct  9  2020 test_params_grib2_tbl_new.f90
```

**Comment by BoiVuong-NOAA** [comment]
we need to test new parameters and it is test_params_grib2_tbl_new.f90.    I need to postpone the test.  Because I just receive a request from NCO to help them troubleshoot RAP products on WCOSS2.  Do you have some to work on it ?

**Comment by edwardhartnett** [comment]
How exactly is this test run?

**Comment by BoiVuong-NOAA** [comment]
This test will give the grib2 table by discipline, category and parameter number of parameters abbreviation (i.e., TMP, HGT, ...)

**Comment by edwardhartnett** [comment]
Our current test coverage is 31%. We can do better.

![image](https://user-images.githubusercontent.com/38856240/186167370-bf650416-8225-4133-9db7-2d652e1c3630.png)

**Comment by edwardhartnett** [comment]
With PR #69 we are up to %83 code coverage. This is much better.

**Comment by edwardhartnett** [comment]
![image](https://user-images.githubusercontent.com/38856240/186411864-99d053dd-6f76-4e17-b01d-2083a792c274.png)
