### ISSUE TITLE
Remove legacy build instructions and files from tests directory

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2tmpl#37]
Seems like we have one unit test, and it is being run by CMake and in the CI.

@BoiVuong-NOAA and @kgerheiser are we running the full set of tests from CMake?

If so, let's remove all the files we don't need for that...

**Comment by BoiVuong-NOAA** [comment]
I do not know about tests from CMake.  So, I will not continue to work on test_params_grib2_tbl_new.f90.

**Comment by edwardhartnett** [comment]
Are you going to add test code for your open PR?

Are there tests in the tests directory that are not being run by CMake?

What is test_params_grib2_tbl_new.f90?

**Comment by BoiVuong-NOAA** [comment]
I can modify the test code to add some new fields.  I think these tests run by CMake. But, We only need test_params_grib2_tbl_new.f90. 
The test_params_grib2_tbl_new.f90 uses to test new fields that add in the params_grib2_tbl_new file.
