### ISSUE TITLE
What is src/sort_params_grib2_tbl.f90?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2tmpl#40]
What is the purpose of this program?

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA what is the purpose of this program?

Why can a regular unix sort command not be used?

**Comment by BoiVuong-NOAA** [comment]
The purpose of this program is to sort all parameters in the file params_grib2_tbl_new.  Jeff gave us a sort routine. Please ask Jeff.

**Comment by edwardhartnett** [comment]
@jbathegit can you shed some light on this question?

**Comment by BoiVuong-NOAA** [comment]
The params_grib2_tbl_new.text is a text format and all parameters is unsorted to a file params_grib2_tbl_new.   This file will be used in g2tmpl library.

**Comment by edwardhartnett** [comment]
OK, that raises the question: why not just keep the sorted list, and add new entries in their proper sorted places?

**Comment by BoiVuong-NOAA** [comment]
Good question. Some users try to add new entries for their testing in the sorted file but not in the proper places. Therefore, it caused the program runs slow.   The purpose of the file params_grib2_tbl_new.text is used to keep a log of information for adding or removing any parameters or adding new grib2 tables, etc.   (it is same as a log file)
