### ISSUE TITLE
Add these parameters (GOES-18 brightness temperatures) to the grib2 file in G2TMPL library.. 

### ISSUE THREAD

**Issue by BoiVuong-NOAA** [NOAA-EMC/NCEPLIBS-g2tmpl#52]
Dr. William E. Lewis has requested to add GOES-18 brightness temperatures to the grib2 table 4-2-3-192.   They are following:
 Simulated Brightness Temperature for ABI GOES-18, Band-7     K    SBTA187
Simulated Brightness Temperature for ABI GOES-18, Band-8     K    SBTA188
Simulated Brightness Temperature for ABI GOES-18, Band-9     K    SBTA189
Simulated Brightness Temperature for ABI GOES-18, Band-10    K    SBTA1810
Simulated Brightness Temperature for ABI GOES-18, Band-11     K    SBTA1811
Simulated Brightness Temperature for ABI GOES-18, Band-12     K    SBTA1812
Simulated Brightness Temperature for ABI GOES-18, Band-13     K    SBTA1813
Simulated Brightness Temperature for ABI GOES-18, Band-14     K    SBTA1814
Simulated Brightness Temperature for ABI GOES-18, Band-15     K    SBTA1815
Simulated Brightness Temperature for ABI GOES-18, Band-16     K    SBTA1816
These parameters (above) need to update in two files in G2TMPL library.  They are following:
1. params_grib2_tbl_new
2. params_grib2_tbl_new.text
Please see "edit_params_grib2_table.README in " to add parameter in /NCEPLIBS-g2tmpl/src/

I have updated the WMO GRIB2 table 4-2-3 on NCEP WMO GRIB2 Documentation.  Please see grib2 table at this link: 
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-3-192.shtml

The new parameter numbers are from 77 to 85 for "Simulated Brightness Temperature for ABI GOES-18"

Let me know if you have any questions.
Thanks, Boi

**Comment by Hang-Lei-NOAA** [comment]
Has started a draft for this change

**Comment by kgerheiser** [comment]
@Hang-Lei-NOAA check out this branch @BoiVuong-NOAA created.

https://github.com/BoiVuong-NOAA/NCEPLIBS-g2tmpl/commit/7ed1429b746c4bd425c594751bfd7bf2d0e83e51

**Comment by Hang-Lei-NOAA** [comment]
Okay, Boi has already did so. Then we just need to merge it in

**Comment by BoiVuong-NOAA** [comment]
Thanks, Hang and Kyle

**Comment by Hang-Lei-NOAA** [comment]
Good Job! We need to tag it and release.

**Comment by BoiVuong-NOAA** [comment]
You do all these tasks, right ?

**Comment by Hang-Lei-NOAA** [comment]
Yes, We can do it for release
v1.10.1
<https://github.com/NOAA-EMC/NCEPLIBS-g2tmpl/tree/v1.10.1>1

**Comment by Hang-Lei-NOAA** [comment]
Tag v1.10.1 made
