### ISSUE TITLE
Add Brown Carbon Dry

### ISSUE THREAD

**Issue by BoiVuong-NOAA** [NOAA-EMC/NCEPLIBS-g2tmpl#55]
Kate Zang requests to update G2TMPL library on Hera to add "Brown Carbon Dry"  to the grib2 table "CODE TABLE 4.230" for the UPP branch develop in UFS-Aerosols model.

**Comment by Hang-Lei-NOAA** [comment]
And create new tag v1.10.2 with this modification.

**Comment by kgerheiser** [comment]
Fixed with #56

**Comment by BoiVuong-NOAA** [comment]
Thanks, Hang.
