### ISSUE TITLE
Error in make procedure

### ISSUE THREAD

**Issue by stephentjemkes** [NOAA-EMC/NCEPLIBS-g2tmpl#88]
Hi,
I am trying to install the UPP package on my local machine which runs Ubuntu 22.04
it depends on the EMC stack
What is really appreciated is the systematic use of cmake throughout the entire stack
What is a bit unfortunate is that some applications have a different approach to cmake. 

the g2tmp is one of the prerequisites for upp. cloned g2tmp and i am use tag v.1.10.2
a prefix has been defined where i want the application to be installed 
export PREFIX=${HOME}/uppapp
cmake process has been initiated by
rm -rf build; mkdir build; cd build

cmake .. -DCMAKE_PREFIX_PATH=$PREFIX -DCMAKE_INSTALL_PREFIX=$PREFIX

to ensure that any prerequisites for g2tmp are found. 

-- The C compiler identification is GNU 11.3.0
-- The Fortran compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /bin/gfortran - skipped
-- Setting build type to 'Release' as none was specified.
-- Configuring done
-- Generating done

make completed successfully
make install however tried to install cmake related documents under root partition and not in $PREFIX

**CMake Error at src/cmake_install.cmake:82 (file):
  file INSTALL cannot copy file
  "/home/stephenuppapp/build/NCEPLIBS-g2tmpl/build/g2tmpl-config.cmake" to
  "/cmake/g2tmpl/g2tmpl-config.cmake": Permission denied.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)**

the make install procedure should copy the g2tmpl-config.cmake file to ${PREFIX}/cmake/g2tmpl/

There is a suggestion  that there is a minor update needed for the installation procedure
best
stephen

**Comment by edwardhartnett** [comment]
I believe this has been fixed and the fix will appear in the next release.
